// Astro 5 Content Collections.
// One collection: posts (replaces the previous life + craft split).
// URL slugs are generated by src/pages/[...slug].astro via postSlug() —
// the slug() option does NOT belong in the collection config when using
// the glob() loader. Keeping that responsibility on the page route.

import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const posts = defineCollection({
  loader: glob({ pattern: '*.md', base: './src/content/posts' }),
  schema: z.object({
    title: z.string(),
    date: z.coerce.date(),
    categories: z.union([z.string(), z.array(z.string())]).default('uncategorized'),
    tags: z.array(z.string()).default([]),
    // Hux Jekyll frontmatter used a `catalog: true` flag on most posts;
    // we keep it as a no-op in Astro (no renderer cares) so old posts
    // migrate without error.
    catalog: z.boolean().default(false),
    summary: z.string().optional(),
  }),
});

export const collections = { posts };