// Astro 5 Content Collections.
// One collection: posts (replaces the previous life + craft split).
// URL slugs are generated by src/pages/[...slug].astro via postSlug() —
// the slug() option does NOT belong in the collection config when using
// the glob() loader. Keeping that responsibility on the page route.

import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';
import path from 'node:path';

const posts = defineCollection({
  loader: glob({
    pattern: '*.md',
    base: './src/content/posts',
    // Astro's default generateId runs filenames through github-slugger,
    // which lowercases ("iOS-App-thin" → "ios-app-thin"). That breaks
    // a decade of 百度/GSC-indexed Jekyll URLs. We use the raw file
    // stem instead so case is preserved exactly as Jekyll wrote it.
    // The 11-char "YYYY-MM-DD-" prefix is stripped by postSlug().
    generateId: ({ entry }) => path.parse(entry).name,
  }),
  schema: z.object({
    title: z.string(),
    date: z.coerce.date(),
    categories: z.union([z.string(), z.array(z.string())]).default('uncategorized'),
    tags: z.array(z.string()).default([]),
    // Hux Jekyll frontmatter used a `catalog: true` flag on most posts;
    // we keep it as a no-op in Astro (no renderer cares) so old posts
    // migrate without error.
    catalog: z.boolean().default(false),
    summary: z.string().optional(),
  }),
});

export const collections = { posts };